### ISSUE TITLE
feature request: methods for interacting with services

### ISSUE THREAD

**Issue by heylix** [asymmetricia/ghastly#1]
(maybe I'll write this myself once I'm not as rusty in Golang anymore)

**Comment by pdbogen** [comment]
I can get started on this, for sure. PRs are welcome, too.

Are you more interested in API support, CLI support, or terraform support? Any particular use case you'd like to share, so I know what to focus on?

**Comment by heylix** [comment]
I didn't manage to get the project to compile properly, so I'll have to read up on Golang again. Joined #golang:matrix.org and hopefully get an answer there. You could help if you like ;)

>Are you more interested in API support, CLI support, or terraform support?

API/CLI, thank you for asking. Currently not using this in Terraform, nor do I plan to.

I'd really like to integrate my own workstations and custom scripts on servers into the automations, e.g. "make coffee when I start my workstation in the morning and didn't press the do-not-make-coffee-button" or "if the following MAC address connects to our network and someone authenticates via Keycloak, mark them as present".
