### ISSUE TITLE
m1 mac build?

### ISSUE THREAD

**Issue by That-Dude** [asymmetricia/ghastly#2]
Hi, ghastly is exactly what I've been looking for - thanks so much for creating it!

It's not vital by any means but an m1 macOS build would be cool, it actually runs fine under rosetta2 but I'm trying to go m1 all the way.

**Comment by asymmetricia** [comment]
Hi! I'm glad you find it useful / interesting. I've added darwin arm64 to the release automation and cut a new release, so as of v0.5 you should be able to grab native M1 binaries. Please raise an issue if you run into any problems or if there are any features you'd like to see!

:heart: Tricia
